dataset:
  root: ./data/real/objects_1211
  clip: 384
  size: 128
  background: 0
  target_size: 128
  color: g

split: 2cm_384x128x128

rsd:
  t: 384
  d: 64
  h: 128
  w: 128
  in_plane: 1
  wall_size: 2
  bin_len: 0.02
  zmin: 0.5
  zmax: 2.5
  scale_coef: 2
  n_cycles: 4
  ratio: 0.1

batch_size: 1
n_workers: 12