dataset:
  root: ./data/real/objects_1211
  clip: 256
  size: 32
  background: 0
  target_size: 32
  color: g

split: 3cm_256x32x32

rsd:
  t: 256
  d: 64
  h: 32
  w: 32
  wall_size: 2
  bin_len: 0.03
  zmin: 0.5
  zmax: 2.5
  scale_coef: 1
  n_cycles: 4
  ratio: 0.1

batch_size: 1
n_workers: 12