dataset:
  root: ./data/synthetic/letters
  clip: 512
  size: 256
  background: 0
  target_size: 256
  color: gray

split: val_unseen_objs_256

rsd:
  t: 512
  d: 64
  h: 256
  w: 256
  in_plane: 1
  wall_size: 2
  bin_len: 0.01
  zmin: 0
  zmax: 2
  scale_coef: 4
  n_cycles: 4
  ratio: 0.1

batch_size: 1
n_workers: 12